from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

rus_types = InlineKeyboardMarkup()
rus_123 = InlineKeyboardButton('1-3', callback_data='rus_123')
rus_4 = InlineKeyboardButton('4', callback_data='rus_4')
rus_5 = InlineKeyboardButton('5 (мало заданий)', callback_data='rus_5')
rus_6 = InlineKeyboardButton('6', callback_data='rus_6')
rus_7 = InlineKeyboardButton('7', callback_data='rus_7')
rus_8 = InlineKeyboardButton('8', callback_data='rus_8')
rus_9 = InlineKeyboardButton('9', callback_data='rus_9')
rus_10 = InlineKeyboardButton('10', callback_data='rus_10')
rus_11 = InlineKeyboardButton('11', callback_data='rus_11')
rus_12 = InlineKeyboardButton('12', callback_data='rus_12')
rus_13 = InlineKeyboardButton('13С', callback_data='rus_13')
rus_14 = InlineKeyboardButton('14С', callback_data='rus_14')
rus_15 = InlineKeyboardButton('15', callback_data='rus_15')
rus_16 = InlineKeyboardButton('16', callback_data='rus_16')
rus_17 = InlineKeyboardButton('17', callback_data='rus_17')
rus_18 = InlineKeyboardButton('18', callback_data='rus_18')
rus_19 = InlineKeyboardButton('19', callback_data='rus_19')
rus_20 = InlineKeyboardButton('20', callback_data='rus_20')
rus_21 = InlineKeyboardButton('21', callback_data='rus_21')
exit = InlineKeyboardButton('Назад ↩️', callback_data = 'exit')
rus_pan = rus_types.add(rus_4, rus_5, rus_6).add(rus_7, rus_8, rus_15, exit)